<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>de.codingair</groupId>
    <artifactId>WarpSystem</artifactId>
    <version>5.0.3_Hotfix-1</version>
    <packaging>pom</packaging>

    <modules>
        <module>WarpSystem-Core</module>
        <module>WarpSystem-Spigot-v1.8</module>
        <module>WarpSystem-Spigot</module>
        <module>WarpSystem-Spigot-Free</module>
        <module>WarpSystem-Bundle-Free</module>
        <module>WarpSystem-Spigot-Premium</module>
        <module>WarpSystem-Bundle-Premium</module>
        <module>WarpSystem-Proxy</module>
    </modules>

    <repositories>
        <repository>
            <id>placeholderapi</id>
            <url>https://repo.extendedclip.com/content/repositories/placeholderapi/</url>
        </repository>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
        <repository>
            <id>papermc</id>
            <url>https://papermc.io/repo/repository/maven-public/</url>
        </repository>
        <repository>
            <id>spigot-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>
        <repository>
            <id>ess-repo</id>
            <url>https://ci.ender.zone/plugin/repository/everything/</url>
        </repository>
        <repository>
            <id>minecraft-repo</id>
            <url>https://libraries.minecraft.net/</url>
        </repository>
        <!--    RedisBungee    -->
        <repository>
            <id>md_5-snapshots</id>
            <url>http://repo.md-5.net/content/repositories/snapshots/</url>
        </repository>
    </repositories>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>21.0</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>com.github.CodingAir</groupId>
                <artifactId>CodingAPI</artifactId>
                <version>1.25</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>com.github.CodingAir</groupId>
                <artifactId>PacketManagement</artifactId>
                <version>1.11</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>de.codingair</groupId>
                <artifactId>WarpSystem-v1.8</artifactId>
                <version>1.0-SNAPSHOT</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>com.github.CodingAir</groupId>
                <artifactId>WarpSystem-API</artifactId>
                <version>5.0.0</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>io.papermc</groupId>
                <artifactId>paperlib</artifactId>
                <version>1.0.5</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.spigotmc</groupId>
                <artifactId>spigot-api</artifactId>
                <version>1.17-R0.1-SNAPSHOT</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>me.xanium</groupId>
                <artifactId>GemsEconomy</artifactId>
                <version>4.8.3</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.black_ixx</groupId>
                <artifactId>PlayerPoints</artifactId>
                <version>2.1.4</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>net.ess3</groupId>
                <artifactId>EssentialsX</artifactId>
                <version>2.17.2</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>com.github.MilkBowl</groupId>
                <artifactId>VaultAPI</artifactId>
                <version>1.7</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>me.clip</groupId>
                <artifactId>placeholderapi</artifactId>
                <version>2.10.9</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>com.mojang</groupId>
                <artifactId>authlib</artifactId>
                <version>1.5.21</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>com.github.TaglineTech</groupId>
                <artifactId>Trevor</artifactId>
                <version>master-d32606d677-1</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>com.imaginarycode.minecraft</groupId>
                <artifactId>RedisBungee</artifactId>
                <version>0.3.8-SNAPSHOT</version>
                <scope>provided</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>